services:
  # Backend Laravel
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bry_backend
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel
    depends_on:
      - db
    volumes:
      - backend_storage:/var/www/html/storage
      - backend_cache:/var/www/html/bootstrap/cache
    networks:
      - bry_network

  # Frontend Angular
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bry_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - bry_network

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: bry_database
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    # ports:
    #   - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bry_network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: bry_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: laravel
      PMA_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - bry_network

volumes:
  backend_storage:
  backend_cache:
  db_data:

networks:
  bry_network:
    driver: bridge
